#:kivy 1.0.9

ScreenManagement:
    MenuScreen:
    AnotherScreen:

<SplashScreen>:    
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'splash-screen.jpg'

    Label:
        text: "Loading..."
        center_x: root.width/2
        color: 0,1,0,0

<MenuScreen>:
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'main-menu.jpg'

    GridLayout:
        cols: 2
        rows: 1
        GridLayout:
            cols: 1
            rows: 7
            width: 10
            Label: 
            Label: 
            Label: 
            Label: 
            Label:
            Button:
                color: 0,1,0,
                background_normal: ''
                background_color: 0,0,0,0
                on_release: 
                    root.manager.transition.direction = 'up'
                    root.manager.current = 'camera'
                text: 'V.A.T.S.'
                halign: 'left'
                valign: 'middle'
            Label:             
        Label:

<CameraMode>
    BoxLayout:
        orientation: 'vertical'

        Camera:
            id: camera
            resolution: 399, 299
            play: True

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: '48dp'
            Button:
                text: 'V.A.T.S.'
                on_release:
                    root.FindFace()

            Button:
                text: 'Back'
                on_release: 
                    root.manager.transition.direction = 'down'
                    root.manager.current = 'menu'


<SettingsScreen>:
    BoxLayout:
        Button:
            text: 'My Settings button'
        Button:
            text: 'Back to menu'
            on_press: 
                root.manager.transition.direction = 'right'
                root.manager.current = 'menu'
